# Generated by Django 5.2.6 on 2025-09-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('altura', models.IntegerField()),
                ('imagem', models.CharField(max_length=500)),
            ],
        ),
    ]
